// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'FIREBASE_WEB_API_KEY_REDACTED',
    appId: 'FIREBASE_WEB_APP_ID_REDACTED',
    messagingSenderId: '37458358225',
    projectId: 'health-tier-dev',
    authDomain: 'health-tier-dev.firebaseapp.com',
    storageBucket: 'health-tier-dev.firebasestorage.app',
    measurementId: 'FIREBASE_WEB_MEASUREMENT_ID_REDACTED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'FIREBASE_ANDROID_API_KEY_REDACTED',
    appId: '1:37458358225:android:e0d8c3e98635a61720baf0',
    messagingSenderId: '37458358225',
    projectId: 'health-tier-dev',
    storageBucket: 'health-tier-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'FIREBASE_IOS_API_KEY_REDACTED',
    appId: 'FIREBASE_IOS_APP_ID_REDACTED',
    messagingSenderId: '37458358225',
    projectId: 'health-tier-dev',
    storageBucket: 'health-tier-dev.firebasestorage.app',
    iosBundleId: 'com.ukhyeon.healthtier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'FIREBASE_IOS_API_KEY_REDACTED',
    appId: 'FIREBASE_MACOS_APP_ID_REDACTED',
    messagingSenderId: '37458358225',
    projectId: 'health-tier-dev',
    storageBucket: 'health-tier-dev.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'FIREBASE_WEB_API_KEY_REDACTED',
    appId: 'FIREBASE_WINDOWS_APP_ID_REDACTED',
    messagingSenderId: '37458358225',
    projectId: 'health-tier-dev',
    authDomain: 'health-tier-dev.firebaseapp.com',
    storageBucket: 'health-tier-dev.firebasestorage.app',
    measurementId: 'FIREBASE_WINDOWS_MEASUREMENT_ID_REDACTED',
  );

}